from factory import *

sys = Factory(0)
print("-------------- forward kinamatics --------------")
sys.fk()
input()
print("-------------- inverse kinamatics --------------")
sys.ik()
input()
print("-------------- jacobian --------------")
sys.jacob()
input()
print("-------------- T_new --------------")
sys.j()
input()
print("-------------- inverse jacobian --------------")
sys.inv_jacob()
input()
print("-------------- trajectory --------------")
sys.t()
