from robot import *

sys = Factory(0)
print("fk")
print(sys.fk())
print("-------------------")
print("ik")
print(sys.ik())
print("-------------------")
print("jacobian")
sys.j()
print("-------------------")
print("trajectory")
sys.t()
print("-------------------")
